// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnvwcimekdjwixwmoxwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdudndjaW1la2Rqd2l4d21veHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjQzNjgsImV4cCI6MjA1NDEwMDM2OH0.OCcajj4lmk3U6md89CtfPW_Rgp6XE2M9Gv_A3ExNCQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);